### ISSUE TITLE
Enable full build

### ISSUE THREAD

**Issue by sarthakpati** [conda-forge/torch-scatter-feedstock#3]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Currently, this build is working for OSX on CPU, and needs to be extended for Linux and Windows using CPU and GPU.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by sarthakpati** [comment]
Tracking this here: https://github.com/sarthakpati/torch-scatter-feedstock/tree/full_build

**Comment by jchodera** [comment]
@jaimergp may have some insight into what's going wrong here.

**Comment by sarthakpati** [comment]
Thanks, any help on this will be greatly appreciated!

**Comment by jaimergp** [comment]
There are no pytorch builds for Windows AFAIK, so for now we can only do Linux builds.

**Comment by sarthakpati** [comment]
This is done. Thanks a ton to @hmaarrfk and @jaimergp!
